# Generated by Django 4.0.6 on 2022-07-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
